<?php

declare(strict_types=1);

namespace Modufolio\Panel\Tests\Resource;

use Modufolio\Panel\Resource\PanelResourceConfigurator;
use PHPUnit\Framework\TestCase;

/**
 * Which routes a registered resource generates, and who may reach them.
 *
 * `only()` / `except()` are what make graduating to a hand-written controller
 * partial rather than all-or-nothing: keep index and show generated while the
 * form pages are written by hand.
 */
final class PanelResourceConfiguratorTest extends TestCase
{
    private function options(): object
    {
        $configurator = new PanelResourceConfigurator();

        return $configurator->resource('App\\Panel\\EventResource');
    }

    public function testEverythingIsGeneratedByDefault(): void
    {
        $options = $this->options();

        foreach (PanelResourceConfigurator::OPERATIONS as $operation) {
            self::assertTrue($options->generates($operation), $operation . ' should be generated by default');
        }
    }

    public function testOnlyNarrowsToTheNamedOperations(): void
    {
        $options = $this->options()->only(['index', 'show']);

        self::assertTrue($options->generates('index'));
        self::assertTrue($options->generates('show'));
        self::assertFalse($options->generates('create'));
        self::assertFalse($options->generates('edit'));
        self::assertFalse($options->generates('delete'));
    }

    public function testExceptRemovesTheNamedOperations(): void
    {
        $options = $this->options()->except(['create', 'edit']);

        self::assertTrue($options->generates('index'));
        self::assertTrue($options->generates('delete'));
        self::assertFalse($options->generates('create'));
        self::assertFalse($options->generates('edit'));
    }

    /** An unknown operation cannot be smuggled in through only(). */
    public function testOnlyIgnoresOperationsThatDoNotExist(): void
    {
        $options = $this->options()->only(['index', 'teleport']);

        self::assertTrue($options->generates('index'));
        self::assertFalse($options->generates('teleport'));
    }

    /**
     * One group of OR-ed roles: any declared role grants access, and the
     * kernel enforces it before the controller runs.
     */
    public function testRolesBecomeASingleOredGroup(): void
    {
        self::assertSame([], $this->options()->roleGroups(), 'No roles means no role gate.');
        self::assertSame(
            [['ROLE_USER', 'ROLE_ADMIN']],
            $this->options()->roles(['ROLE_USER', 'ROLE_ADMIN'])->roleGroups(),
        );
    }

    public function testThePrefixFallsBackToTheCallersDefault(): void
    {
        self::assertSame('/panel', $this->options()->prefixOr('/panel'));
        self::assertSame('/admin', $this->options()->prefix('/admin/')->prefixOr('/panel'));
    }

    public function testRegisteredResourcesAreReturnedFromTheConfig(): void
    {
        $configurator = new PanelResourceConfigurator();
        $configurator->resource('App\\Panel\\EventResource')->roles(['ROLE_USER']);
        $configurator->resource('App\\Panel\\ActorResource');

        $config = $configurator->buildConfig();

        self::assertCount(2, $config);
        self::assertArrayHasKey('App\\Panel\\EventResource', $config);
    }
}
