<?php

declare(strict_types=1);

namespace Modufolio\Panel\Tests\Resource;

use Modufolio\Panel\Resource\PanelResourceConfigurator;
use Modufolio\Panel\Resource\PanelResourceOptions;
use Modufolio\Panel\Tests\Routing\ReadOnlyResource;
use Modufolio\Panel\Tests\Routing\WritableResource;
use PHPUnit\Framework\TestCase;

/**
 * Which routes a registered resource generates, and who may reach them.
 *
 * `only()` / `except()` are what make graduating to a hand-written controller
 * partial rather than all-or-nothing: keep index and show generated while the
 * form pages are written by hand.
 */
final class PanelResourceConfiguratorTest extends TestCase
{
    private function options(): PanelResourceOptions
    {
        $configurator = new PanelResourceConfigurator();

        return $configurator->resource(ReadOnlyResource::class);
    }

    public function testEverythingIsGeneratedByDefault(): void
    {
        $options = $this->options();

        foreach (PanelResourceConfigurator::OPERATIONS as $operation) {
            self::assertTrue($options->generates($operation), $operation . ' should be generated by default');
        }
    }

    public function testOnlyNarrowsToTheNamedOperations(): void
    {
        $options = $this->options()->only(['index', 'show']);

        self::assertTrue($options->generates('index'));
        self::assertTrue($options->generates('show'));
        self::assertFalse($options->generates('create'));
        self::assertFalse($options->generates('edit'));
        self::assertFalse($options->generates('delete'));
    }

    public function testExceptRemovesTheNamedOperations(): void
    {
        $options = $this->options()->except(['create', 'edit']);

        self::assertTrue($options->generates('index'));
        self::assertTrue($options->generates('delete'));
        self::assertFalse($options->generates('create'));
        self::assertFalse($options->generates('edit'));
    }

    /** An unknown operation cannot be smuggled in through only(). */
    public function testOnlyIgnoresOperationsThatDoNotExist(): void
    {
        $options = $this->options()->only(['index', 'teleport']);

        self::assertTrue($options->generates('index'));
        self::assertFalse($options->generates('teleport'));
    }

    /** Every concrete resource under the directory, alphabetically, and nothing that is not one. */
    public function testDiscoverRegistersTheConcreteResourcesUnderADirectory(): void
    {
        $configurator = new PanelResourceConfigurator();
        $configurator->discover(__DIR__ . '/../Fixture', 'Modufolio\\Panel\\Tests\\Fixture');

        $classes = array_keys($configurator->buildConfig());

        self::assertContains(\Modufolio\Panel\Tests\Fixture\MovieResource::class, $classes);
        self::assertContains(\Modufolio\Panel\Tests\Fixture\DerivedMovieResource::class, $classes);
        self::assertNotContains(\Modufolio\Panel\Tests\Fixture\StubListQuery::class, $classes, 'Not a resource.');
        self::assertNotContains(\Modufolio\Panel\Tests\Fixture\Entity\Movie::class, $classes, 'Subdirectories are walked, entities are not resources.');
        self::assertSame($classes, (static function (array $c): array { sort($c); return $c; })($classes), 'Alphabetical, not filesystem order.');
    }

    public function testDiscoverRefusesAPathThatIsNotADirectory(): void
    {
        $this->expectException(\InvalidArgumentException::class);

        (new PanelResourceConfigurator())->discover(__DIR__ . '/nope', 'X');
    }

    public function testThePrefixFallsBackToTheCallersDefault(): void
    {
        self::assertSame('/panel', $this->options()->prefixOr('/panel'));
        self::assertSame('/admin', $this->options()->prefix('/admin/')->prefixOr('/panel'));
    }

    public function testRegisteredResourcesAreReturnedFromTheConfig(): void
    {
        $configurator = new PanelResourceConfigurator();
        $configurator->resource(ReadOnlyResource::class);
        $configurator->resource(WritableResource::class);

        $config = $configurator->buildConfig();

        self::assertCount(2, $config);
        self::assertArrayHasKey(ReadOnlyResource::class, $config);
    }
}
